### ISSUE TITLE
Explicitly set the state to on/off

### ISSUE THREAD

**Issue by michaljonik** [drmibell/node-red-contrib-random-event-generator#2]
I would love to be able to explicitly set the state to on of off based on the input control message.
That would make the behaviour more deterministic without a need to store the current state outside in another node.
It would be controlled via a payload or a specific message attribute, eg:
{"topic": "control", "paylod": "on"}

**Comment by drmibell** [comment]
That seems like a good idea. I think "start" and "stop" might be better commands than "on/off". For backward compatibility, I would like to keep the "toggle" command, and I'm trying to find a way to avoid breaking any existing flows. I will let you know as soon as I have something you can test.

**Comment by michaljonik** [comment]
Excellent, thanks!

**Comment by drmibell** [comment]
I just pushed a new branch called `start_stop_controls`, which should meet your needs. I am still testing it and working on documentation, but it would be very helpful if you could try it out and report any issues. Thanks.

**Comment by michaljonik** [comment]
Michael, I checked my node-red installation (home assistant addon on Docker) but I have no idea where the random-event-generator module is installed. Are you able to provide any hints?

**Comment by drmibell** [comment]
I am not sure how much I can help, since I do not use either Home Assistant or Docker. In a typical installation, the node files would be found  at `~/.node-red/node_modules/node-red-contrib-random-event-generator/`, and they could be replaced by the new branch. If you can't work out the equivalent process for your configuration, you might check the Home Assistant documentation or forums for how to update a Node-Red node.

**Comment by michaljonik** [comment]
I found the location: 
`/config/node-red/node_modules/node-red-contrib-random-event-generator`

The changes works perfectly.
However when a flow with this node is deployed I'm seeing an error in the debug window:
```
msg : error
"TypeError: Cannot read property 'toLowerCase' of undefined"
```

**Comment by drmibell** [comment]
Thanks for catching that error. It would help me to know whether the node receives an incoming message when the flow starts, that is from an `inject` node configured to "inject once after x seconds."

**Comment by michaljonik** [comment]
Yes, it does receive it. That is my test flow:
<img width="594" alt="Zrzut ekranu 2020-10-30 o 09 33 32" src="https://user-images.githubusercontent.com/7828380/97677719-01582280-1a93-11eb-8d31-34fbc3f599a3.png">
```json
[{"id":"74228c59.4ada54","type":"inject","z":"d1c6e7b1.fe8b88","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":"5","topic":"control","payload":"start","payloadType":"str","x":230,"y":2080,"wires":[["87b9c59b.496028"]]},{"id":"f233315c.eeaef","type":"debug","z":"d1c6e7b1.fe8b88","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":2100,"wires":[]},{"id":"fada286f.3e9e08","type":"inject","z":"d1c6e7b1.fe8b88","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":"10","topic":"control","payload":"stop","payloadType":"str","x":230,"y":2140,"wires":[["87b9c59b.496028"]]},{"id":"87b9c59b.496028","type":"event","z":"d1c6e7b1.fe8b88","name":"","controlTopic":"control","startCmd":"START","stopCmd":"STOP","meanInterval":1,"distribution":"uniform","minInterval":1,"maxInterval":2,"outputTopic":"event","outputPayload":"timestamp","x":450,"y":2100,"wires":[["f233315c.eeaef"]]}]```

**Comment by drmibell** [comment]
I just pushed an update that should resolve the "cannot read property" errors. I also cleaned up the logic a bit, so please check that I have not introduced new bugs.

**Comment by michaljonik** [comment]
I pulled and tested your changed.
However I still see `TypeError: Cannot read property 'toLowerCase' of undefined` when the flow is redeployed.

**Comment by michaljonik** [comment]
Strange. I realised I had another node in my project. That one I did not touch so it did not have start/stop commands configured. When I modified it the errors stopped appearing. Now even if I leave it empty or insert a new node I don't have those errors anymore.
So it looks good now.

**Comment by drmibell** [comment]
Thanks for suggesting the new feature and taking the time to test it. I will merge the `start_stop_controls` branch into the master shortly and upload a new version to npm. After that, I will close this issue, but please feel free to let me know if you have any further issues or suggestions.

**Comment by drmibell** [comment]
Added in version 0.1.0
